title: Chris Koknat
logo: "/images/LinkedInCircle2.jpg?raw=true"
description:
  Developer specializing in Perl & Python
  <br><br>
  <a href="https://www.linkedin.com/in/chriskoknat/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
